(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
  width: 550,
  height: 600,
  fps: 24,
  color: "#FFFFFF",
  opacity: 1.00,
  manifest: []
};



lib.ssMetadata = [];


// symbols:



(lib.Tween6 = function(mode,startPosition,loop) {
  this.initialize(mode,startPosition,loop,{});

  // Layer 1
  this.shape = new cjs.Shape();
  this.shape.graphics.f().s("#333333").ss(1.8,1,1).p("AADAAQgDAAgCAC");
  this.shape.setTransform(61.8,-37);

  this.shape_1 = new cjs.Shape();
  this.shape_1.graphics.f().s("#333333").ss(1.8,1,1).p("AhLknQALAQAEANQADAKADASQACAMAKAWQAHAZAKA0QABAFAFAJQAFAJABAFQABADgBAGQgBAGABADQABAEAEAIIADAQQACAHACAEQAFAPACALQAAACAAAFQgBAFAAACQACAEAGAJQAGAJACAFQAAACgBAEQgBAFAAACQADALAHAVQALApABALQABAHAAAMQAAALACAIQACAJAHATQAGARACALQADANAHAaQAHAZgCAQ");
  this.shape_1.setTransform(69.2,-7);

  this.shape_2 = new cjs.Shape();
  this.shape_2.graphics.f().s("#333333").ss(1.8,1,1).p("AjPCSQAEgBACgCQADgEACgCQAIgFAPgHQAMgFAQgNQAIgHASgPQAHgGAKgHQARgMAlgYQAkgXARgNIAmgbQAQgOAjgXQAGgFALgLQAMgLAIgGQAfgWALgGQABAAAPgNQAKgIAJAC");
  this.shape_2.setTransform(20.5,28.1);

  this.shape_3 = new cjs.Shape();
  this.shape_3.graphics.f().s("#333333").ss(1.8,1,1).p("AjhCpICLhXQAygiBDg3IASgPQALgJAfgbQAZgXAQgNIAOgKQAIgFANgOQAMgNAJgFQALgFAJgHQAGgFANgK");
  this.shape_3.setTransform(19,34.5);

  this.shape_4 = new cjs.Shape();
  this.shape_4.graphics.f().s("#333333").ss(1.8,1,1).p("AnwB8QALACANgGQASgIAGgBQAKgCATACQAJgBAMgDQAHgCANgFQAPgFAfgFQAegGAPgFQAwgQAqgHQAegFA8gMQALgCAjgJQAcgHARgBQAYgCAvgNQANgCAYgCQAYgBAMAAQAagFAugWQAKgFATgCQAVgCAJgDQAFgCATgIQAPgHAKgCQAfgIAJgDQAKgEAkgOQAdgLASgGQAFgBANgDQALgCAGgCQAEgBAHgFQAHgEADgB");
  this.shape_4.setTransform(-55.7,61.6);

  this.shape_5 = new cjs.Shape();
  this.shape_5.graphics.f().s("#333333").ss(1.8,1,1).p("AgVhcIAGABQAHAdAUA+QAPA3gIAm");
  this.shape_5.setTransform(-20.4,27.8);

  this.shape_6 = new cjs.Shape();
  this.shape_6.graphics.f().s("#333333").ss(1.8,1,1).p("AANBOQABgXgHgeQgHgggEgSQgFgRgCgJQgBgIgBgHIAAgL");
  this.shape_6.setTransform(-24.1,27.2);

  this.shape_7 = new cjs.Shape();
  this.shape_7.graphics.f().s("#333333").ss(1.8,1,1).p("AgQhLQgBAJAJAZQAVA7AEA6");
  this.shape_7.setTransform(-27.9,27.5);

  this.shape_8 = new cjs.Shape();
  this.shape_8.graphics.f().s("#333333").ss(1.8,1,1).p("AkEA6IABAGQADgBARgJQANgGAHgDQAFgBANgBQALgBAGgCQAXgJAKgDQApgIBQgTQAKgBAdgEQAZgEAQgEQAIgCAYgHQATgGANgCQAIgBBHgRQBAgPAEAA");
  this.shape_8.setTransform(-52.2,57.9);

  this.shape_9 = new cjs.Shape();
  this.shape_9.graphics.f().s("#333333").ss(1.8,1,1).p("Agsi3IAAAHQACAoAXBAQAYBIAEAcQABAIACANQABAMAEAJQAGAQABAdQAAAOAGAUQAJAfAAAEQAGABAAgI");
  this.shape_9.setTransform(-83.6,45.9);

  this.shape_10 = new cjs.Shape();
  this.shape_10.graphics.f().s("#333333").ss(1.8,1,1).p("Aj3BKIADABQAGgFANgDQAHgBAOgDQBLgWAXgJQAIgDARgDQAQgEAHgDQARgGAfgNQAUgGAqgNQAKgEAUgDQAUgDAKgEQAhgMARgEQAKgCAKgFQAFgDANgHQAIgEAPgBQATgBAGgCIgDAE");
  this.shape_10.setTransform(-62.5,20.7);

  this.shape_11 = new cjs.Shape();
  this.shape_11.graphics.f().s("#333333").ss(1.8,1,1).p("AgHgtQAGARACAcQAFAlACAJ");
  this.shape_11.setTransform(-26.7,46.1);

  this.shape_12 = new cjs.Shape();
  this.shape_12.graphics.f().s("#333333").ss(1.8,1,1).p("AgxiGQgBAIAIAJQAMAPABAAQAEAJACAOQADAMAMAWQAMAaADAIQAEALAJATQAIATACAPQAAADAAANQAAAKACAHQABACAKAVQAHAOAAAM");
  this.shape_12.setTransform(-32.6,27.2);

  this.shape_13 = new cjs.Shape();
  this.shape_13.graphics.f().s("#333333").ss(1.8,1,1).p("AhAgMIAUgCQAWgEAMgDQAJgDAPAAQATgBAIgCQACAAAGgFQAFgEAFACQAHACAAAFIAAAKQAEAOAJAkQgOAEgVgCQgYgEgLgCQgIgBgRAAQgRAAgKgCIgBgBQgMgCgFgCQgKgCgHAB");
  this.shape_13.setTransform(-46.7,35.1);

  this.shape_14 = new cjs.Shape();
  this.shape_14.graphics.f().s("#333333").ss(1.8,1,1).p("AA1gnIAFgBQgBgIgIADQgIAGgDABQgGABgMAAQgMABgFABQgYADgNAEQgDABgMAGQgJAEgGABQABACAJAPQAGANACAIQAHAXACABQAEAEAPgOQAHgHAMgOQAMgMAKgFQAFgDALgLQAKgKAHgDQAEgCAFgB");
  this.shape_14.setTransform(-62.7,40.5);

  this.shape_15 = new cjs.Shape();
  this.shape_15.graphics.f().s("#333333").ss(1.8,1,1).p("Ag8hkQgFAKAAABQgBAEAEAHIAOAaQADAHAIAHQAJAHACAEQABACAFAPIABAKQAAAAgDADQgDADgBACQgBAFACAKIAAA0QAAAFAGANQAAADgFAJQgDAIADAHQAFgBAIgIQALgIAAgCQAFgDANgFQALgEAGgEIAMgJQAPgFAAgBQAIgKgIgMQgBAAgPgPQgDgDgEgGQgEgGgDgDQgLgEgCgDQgEgDgBgKIAAgpQgBg2ACgTQgDAEgKADQgLADgCABQgNAIgCAAQgEABgJgBQgJgCgEADIgBAF");
  this.shape_15.setTransform(-52.7,38.4);

  this.shape_16 = new cjs.Shape();
  this.shape_16.graphics.f().s("#333333").ss(1.8,1,1).p("AhkgBQATAAAlgCQAiAAAUADQAKABAQAAQAJAAARgBQADAAAIAAQAIAAAEAAQAFABAGACIAEAB");
  this.shape_16.setTransform(157.9,-10.9);

  this.shape_17 = new cjs.Shape();
  this.shape_17.graphics.f().s("#333333").ss(1.8,1,1).p("AhjgcIAAgDIAAAAQAMgBAWgWQAagZAUgMQAOgJATgSQAPgPAFABQACALADAJQACAHAEAQQADAPADAHQAJAeABAJQACAJAEANIAEAOIAIATQACAFABALQABAJAEASQAAAEADAIQACAJABAEQABAFAAALQABADADAIQACAHABAE");
  this.shape_17.setTransform(157.6,-24.5);

  this.shape_18 = new cjs.Shape();
  this.shape_18.graphics.f().s("#333333").ss(1.8,1,1).p("AgchyQAAAAABACQACAFAAAJQABAJADANQAEAQABAFQABAHABAOQACALADAJQAIAOAAAAQABAHAAALQAAAHAIARQAEAGAAAIQABAFAEAIQAGAJABADQAFAMAAAW");
  this.shape_18.setTransform(138.2,-48.8);

  this.shape_19 = new cjs.Shape();
  this.shape_19.graphics.f().s("#333333").ss(1.8,1,1).p("AhAi3IAAADQAAAKAHARQAHAUALAfQAFANAIAbIAHAPIAEARQABABADAFQACADAAAEQADAMANAuQACAGAHATQAGAPACAKQADAQAOAaQAFAIAKARQAJAOABAM");
  this.shape_19.setTransform(106.1,-3.8);

  this.shape_20 = new cjs.Shape();
  this.shape_20.graphics.f().s("#333333").ss(1.8,1,1).p("AgFhsIAAAEQABADAAAJIACAKQACANAAAWQABAaABAJQACAMAAAWQAAAMgBAXQAAAFAAAKQAAAJABAGQABAIABAO");
  this.shape_20.setTransform(99.1,-33.6);

  this.shape_21 = new cjs.Shape();
  this.shape_21.graphics.f().s("#333333").ss(1.8,1,1).p("AkiBXQAIgCARgEQACgBAKgFQAIgEAGgBQAngIAvgPQAcgIA5gVQBGgXAfgJQAGgBAPgHQANgGAIgBQAEAAAigKQAJgDAcgIQAXgGANgFQALgEAQgEIAhgIQAHgCAOgFIAJAAQAGAAACgDQADAEAEgC");
  this.shape_21.setTransform(75.5,-14.4);

  this.shape_22 = new cjs.Shape();
  this.shape_22.graphics.f().s("#333333").ss(1.8,1,1).p("AAZhQIAAADQAAASgKAUQgFAIgDAVQgFAMgBAMQgBAJgLAaQgDAGgDAKQgBACgCAHQgDAHgBAA");
  this.shape_22.setTransform(35.3,-23.5);

  this.shape_23 = new cjs.Shape();
  this.shape_23.graphics.f().s("#333333").ss(1.8,1,1).p("AAFgNQABAEgDADQgDAFAAABIgEAN");
  this.shape_23.setTransform(53.7,32);

  this.shape_24 = new cjs.Shape();
  this.shape_24.graphics.f().s("#333333").ss(1.8,1,1).p("AADhCQAAAQgBAFQgCANAAAhIAAAdQAAAGAAANQgCAMAAAG");
  this.shape_24.setTransform(108.5,22.8);

  this.shape_25 = new cjs.Shape();
  this.shape_25.graphics.f().s("#333333").ss(1.8,1,1).p("AmLhBQAEABAMALQAPAJANAGQATAJAMAHQAFACAMAKQAJAJAHACQAfARAQAHQACABAbAPQAFAEAJACQAFACAJADQAHACANAEQALADAHAFQAKAIAEABQAEABACAAQACgBAEgCQADgBALgBQAJgCAFgCQALgDAWgIQATgEAjgMQAGgCAOgGQANgEAJgBQAQgDAkgOQAUgIBQgZQAvgPAcgHIAKgDQAZgJAJgBQAIAAAUgDQAXgDAMgEQAEgBAHgEQAHgCAGAA");
  this.shape_25.setTransform(80.7,34.8);

  this.shape_26 = new cjs.Shape();
  this.shape_26.graphics.f().s("#333333").ss(1.8,1,1).p("AgphxQABAEAFAHIABACIALAdQAXA9ABAKIAEAMQAEARAKAgQADANAHALQAGAJAGARQABABAAACIABAAIgCgD");
  this.shape_26.setTransform(162.3,35.5);

  this.shape_27 = new cjs.Shape();
  this.shape_27.graphics.f().s("#333333").ss(1.8,1,1).p("AhQgxIgEABQAAADAFADQABACAOAFQAKAGAQAJIAjAVQADACAIADQAIAEAEACQAFADAIAIQACABARAHQASAIAIAEQAGAFABAC");
  this.shape_27.setTransform(154.6,31.1);

  this.shape_28 = new cjs.Shape();
  this.shape_28.graphics.f().s("#333333").ss(1.8,1,1).p("AjPgOIABgDIACABQAHACANAAQAQAAAEAAQAGABAKADIAQgBQAMABAVADQALABAYAFQAJABATAAQADAAALAAQAIABAGAAQATAAADAAIAHgBQAEgBADABQAEAAAIACIAMgBQAIAAANAEIAGAAIAAAAQAFgBAJgDIALAAQAOAAADAAQACgBAFAAQAFgBACABQABAAACACQACACACABQAEABAHgBQAGAAALADQAEABAGADQAGACADABQAEABAGAAQAFABAEAC");
  this.shape_28.setTransform(158.6,46.5);

  this.shape_29 = new cjs.Shape();
  this.shape_29.graphics.f().s("#333333").ss(1.8,1,1).p("AimAnQAEgDAKAAQAFAAAJABQAFAAAIgDQAKgEAEAAQAHgBAOgCQAhgHAUgIQAIgCASgDQAPgDAIgEQAOgEASgGQAZgJAbgEQADgBAHAAIAQgEQANgBAEgCQAOgFAGgBIADAAQADgBACABIgCAD");
  this.shape_29.setTransform(142,27.9);

  this.shape_30 = new cjs.Shape();
  this.shape_30.graphics.f().s("#333333").ss(1.8,1,1).p("AhqBlIA5gzQAHgHANgPQAMgPAHgHQAFgFAJgFQALgHAFgFQAHgGAOgLIAOgRQAFgGAJgIQAFgEAKgIIANgNQAAAAAFgEQACgBABgCQACgCAAgC");
  this.shape_30.setTransform(148.5,34.9);

  this.shape_31 = new cjs.Shape();
  this.shape_31.graphics.f().s("#333333").ss(1.8,1,1).p("AhShZQgCgBgBgCIAAABQAAACACAEIAFAFQAFAHAKAIQANALAEAEIAPAUQAEAFAMAJQAFAFAJALQAGAMAFAFQACABAEADQAEACACACQADAEAGAIQADADAGAEQAHAEACACQADAEAEAHQACADAIAFQAHAIAOAQ");
  this.shape_31.setTransform(129,35.5);

  this.shape_32 = new cjs.Shape();
  this.shape_32.graphics.f().s("#333333").ss(1.8,1,1).p("AgjhpQABACABABQACACABABIADAFIAAAAIADAJQABAGAEALQAFAKABAGQABAFACALQABAEAFAHQABAHADAMQADAMAAACQACANAHAQQADAKAJATQADAIAGAdIAAACIADAB");
  this.shape_32.setTransform(155,13.7);

  this.shape_33 = new cjs.Shape();
  this.shape_33.graphics.f().s("#333333").ss(1.8,1,1).p("AgCgCIAFAF");
  this.shape_33.setTransform(150.6,4.9);

  this.shape_34 = new cjs.Shape();
  this.shape_34.graphics.f().s("#333333").ss(1.8,1,1).p("AgCAAIAAABIACAAIAAABIADgB");
  this.shape_34.setTransform(150.6,4.7);

  this.shape_35 = new cjs.Shape();
  this.shape_35.graphics.f().s("#333333").ss(1.8,1,1).p("AgMhGQAAARAFAYQACANAFAZQACAZACAFQABADACAFQAAAMABAAQABAHAEAE");
  this.shape_35.setTransform(118.9,19.3);

  this.shape_36 = new cjs.Shape();
  this.shape_36.graphics.f().s("#333333").ss(1.8,1,1).p("Ai3A1QABgGAIgBQAEAAAIAAQAFgBAKgFQAKgEAGgBQAPgBAKgFQAXgKALgBQASAAATgJQAMgFAXgFQAEgCAKgEQAJgDAFgCQAUgFAogMQAcgHANgGQAEgBAHgBQADgBAJAAQAHAAAEgBQAKgCABgBIAKgE");
  this.shape_36.setTransform(127.3,-31.1);

  this.shape_37 = new cjs.Shape();
  this.shape_37.graphics.f().s("#333333").ss(1.8,1,1).p("AAAAAQAAAAABAA");
  this.shape_37.setTransform(117.4,12.2);

  this.shape_38 = new cjs.Shape();
  this.shape_38.graphics.f().s("#333333").ss(1.8,1,1).p("AijAkQADgBAFgCQAFgBAIAAQAMAAAdgIQAJgCAQAAQALAAAUgKQAHgDARgEQAQgEAHgCQAHgDAQAAQAPAAAIgDQATgIAngKQAHgCANgCQAPgCAEgBIATgD");
  this.shape_38.setTransform(134,8.5);

  this.shape_39 = new cjs.Shape();
  this.shape_39.graphics.f().s("#333333").ss(1.8,1,1).p("AgDAAIAHAA");
  this.shape_39.setTransform(151.2,4.9);

  this.shape_40 = new cjs.Shape();
  this.shape_40.graphics.f().s("#333333").ss(1.8,1,1).p("AhLlJQgBAHAFAQQACAKAEAPQAFASACAHQABAHAFAPQAEAPACAIQAEAXAJAXQADAHAJAfQACAHABAQQACAQACAIQABADADAIQADAHABADQABAFAAAKQABAHABAAQABADACAIQACAHABAEQABAHABANIADAMQABAFAEAJQACAIABAGIAJAtQABAFADAVQADAQACAKQAIAeACARQABAIACAPQAEAOABAGQACAUAEANQADAFAEAJQAEAHAAAIQABALAGAVIAAAE");
  this.shape_40.setTransform(109.2,-21.2);

  this.shape_41 = new cjs.Shape();
  this.shape_41.graphics.f().s("#333333").ss(1.8,1,1).p("AgehqQAAAEACAHQABADACAHQABAGABAKQACANAGAOIAHAXQALAsAOApQAEALAIAUIACAFIAAAF");
  this.shape_41.setTransform(149.2,-6.7);

  this.shape_42 = new cjs.Shape();
  this.shape_42.graphics.f().s("#333333").ss(1.8,1,1).p("AgMhXQAEgBABADQABABAAAFQAAAGADAPQADALAAASQACAWABAHIABAFQAFAbAAAWQAAAIABAEIADAIIAAAO");
  this.shape_42.setTransform(147.2,-27.7);

  this.shape_43 = new cjs.Shape();
  this.shape_43.graphics.f().s("#333333").ss(1.8,1,1).p("AjfA3IAFAAIAKAAQAOgCAXgIQAMgEAYgJQAWgHAPgCQAOgBAagIQAGgBAMgEQALgFAGgBIAIgBQAYgDAAAAIADgBQAHgCAMgGQAMgFAIgBQAbgDAFAAQAJgCAUgJQAFgCAIgBQAJAAAEgBQACAAACgCQAFgCAKABQAHgBALgFIAOgFQAWgGANAA");
  this.shape_43.setTransform(147.7,-18.1);

  this.shape_44 = new cjs.Shape();
  this.shape_44.graphics.f().s("#333333").ss(1.8,1,1).p("AAAgCQAAACAAAD");
  this.shape_44.setTransform(125.7,-12.9);

  this.shape_45 = new cjs.Shape();
  this.shape_45.graphics.f().s("#333333").ss(1.8,1,1).p("AiChWQAFAIAPAHQAHADAIAIQAJAKAFADQAGAEANAGQAOAGAGAFQAMAHAaANQAEACAOAFQAGADANAJQAHAEAMALQANALAGAEQAKAGATANQAPAJAFACQAKAEAAADIABADQgEACgFAB");
  this.shape_45.setTransform(138.9,-3.8);

  this.shape_46 = new cjs.Shape();
  this.shape_46.graphics.f().s("#333333").ss(1.8,1,1).p("AACAAIgDAA");
  this.shape_46.setTransform(150.9,4.9);

  this.shape_47 = new cjs.Shape();
  this.shape_47.graphics.f().s("#333333").ss(1.8,1,1).p("AABAAIgBAA");
  this.shape_47.setTransform(150.4,4.9);

  this.shape_48 = new cjs.Shape();
  this.shape_48.graphics.f().s("#333333").ss(1.8,1,1).p("AhoB4QAAgDAKgMQALgNAUgbQAKgNAOgZQAGgIAPgOIALgOQAHgNAWgRIAggdQABgBAJgLQADgEAMgLQABgCAIgKIAFgEQAEgDAIgF");
  this.shape_48.setTransform(135.5,-24.9);

  this.shape_49 = new cjs.Shape();
  this.shape_49.graphics.f().s("#333333").ss(1.8,1,1).p("AgGCaQgBgHAGgQQABgJAIgeQABgFAGgKQAEgKACgGQABgJAAgEQABgHACgFQAHgJADgFQADgGACgKQAEgNABgCQABgFAEgIQAFgJABgEQAKgRADgKQAHgPgBgEIAAgBQgBgCgDgCQgDgCgIgEQgFgCgJgBQgKAAgEgDQgggMgJgIQgEgDgXgLQgJgGgGgDQgRgIgHgE");
  this.shape_49.setTransform(117.6,-4);

  this.shape_50 = new cjs.Shape();
  this.shape_50.graphics.f().s("#333333").ss(1.8,1,1).p("AAAgCIAAACIAAAD");
  this.shape_50.setTransform(180.8,39.8);

  this.shape_51 = new cjs.Shape();
  this.shape_51.graphics.f().s("#333333").ss(1.8,1,1).p("AgMhdQAAADgCAHQgIAQAAAVIABA4QAAAJgCASQgCASAAAJQAAAFABAMQAAABgEAFQgBAEABADQAEgBACgFQADgGABgBQAEgEAKgEQAEgCACgHIAJgMIADgNIAEgEQAFgJACgHQAGgXgCgLQgBgGgFgSQgBgDABgJQAAgIgCgEQgGgGgCgEQgHgJgJgGg");
  this.shape_51.setTransform(182.1,49.6);

  this.shape_52 = new cjs.Shape();
  this.shape_52.graphics.f().s("#333333").ss(1.8,1,1).p("AADAFQgGgFABgE");
  this.shape_52.setTransform(180.5,39.5);

  this.shape_53 = new cjs.Shape();
  this.shape_53.graphics.f().s("#333333").ss(1.8,1,1).p("AglheIAAAOQABAWAHAWQAAACADAGQADAEAAADQABACAAAJQAAAFACAFQADACAEAIQACAFACAJQAAACADAFQADADAAADQACAEgBAKQABAEADAGQABADACAFQABADAFADIAFAIQABABAEAGQAEAFACAAQAFgRACgIQgBgMABgHQAEgLAAgGQAAgDgBgDQgBgDgBgCQAAgKgBgFQAAgEgDgEQgFgEgCgGIgBgJQgBgDgFgEQgHgHAAAAQgJgKgHgHQgFgFgIgQQgJgRgFgFIAAAN");
  this.shape_53.setTransform(172.9,-21.1);

  this.shape_54 = new cjs.Shape();
  this.shape_54.graphics.f().s("#333333").ss(1.8,1,1).p("AgvhWQgBAEACADQAEAIAAABQABAGACANQACAHAJANQACAFADANQADAMAEADQAKARAEAHQAMAdAEAHQAFAIAGAFQABABADAGQADAEABAAQACgDACgIQADgNACgGQAGgTAAgOQAAgKAAgFQAAgIgDgDQgGgOgIgKQgGgHgMgJQgNgHgFgFQgDgEgCgCQgBgCgLgGQgPgJgFgB");
  this.shape_54.setTransform(147.8,-93.6);

  this.shape_55 = new cjs.Shape();
  this.shape_55.graphics.f().s("#333333").ss(1.8,1,1).p("Ag1A8IABgDIAGgCQABgJANgNQAIgHAMgMIAIgKQANgRAHgJQAMgMABgCQACgDAEgFIALgJQAAgEAEAAIAAAAQABAAADgC");
  this.shape_55.setTransform(130.6,-65.9);

  this.shape_56 = new cjs.Shape();
  this.shape_56.graphics.f().s("#333333").ss(1.8,1,1).p("AAAAiQgBAFABhEIAAgF");
  this.shape_56.setTransform(135.9,-81.1);

  this.shape_57 = new cjs.Shape();
  this.shape_57.graphics.f().s("#333333").ss(1.8,1,1).p("AADhyIAAAFQgBAHgCANQAAAUAABEIAAAPQgBAfAAAQIAAAYQgBAHACANIAAAK");
  this.shape_57.setTransform(135.6,-73.1);

  this.shape_58 = new cjs.Shape();
  this.shape_58.graphics.f().s("#333333").ss(1.8,1,1).p("AimBpIADgFIABAAQAPgTAKgGQAQgIAegRIAfgTQAJgFARgJQAKgHAVgJQATgHAJgIQAKgHAUgLIAKgGQAEgCAKgFQAKgEAEgDQACgBAPgOQAIgHAVgLQAUgLAIgI");
  this.shape_58.setTransform(129.3,-81.4);

  this.shape_59 = new cjs.Shape();
  this.shape_59.graphics.f().s("#333333").ss(1.8,1,1).p("AhxgtIgBgBIAAABQAGAGAOADQAUAFAAAAIBCATQAHACAJAGQAHACAOACQASAFAJAHIABAAQALAHAQAIQAIADAKAGQACACAIADQACACABADIgDAB");
  this.shape_59.setTransform(124.4,-66.7);

  this.shape_60 = new cjs.Shape();
  this.shape_60.graphics.f().s("#333333").ss(1.8,1,1).p("Ag1BXQAFgCAEgEQAGgFAMgYQAIgRAXgoQACgEAVgjQANgYAKgOIADgD");
  this.shape_60.setTransform(107.6,-63);

  this.shape_61 = new cjs.Shape();
  this.shape_61.graphics.f().s("#333333").ss(1.8,1,1).p("AnrBoIASgHIAQgEQADAAALgDQAJgDAGgBQAKgBATABIAYgDQAGAAAKgFQALgFAGAAQAFgBAJAAQAIgBAGgBQAcgLAggEQAMgDA1gQIAUgFQAJgDAQgHQAJgCAQAAQACgBAegHQAIgBASgDQARgCAJgDQAUgDAGgBQAHgCANgFQAJgBARgBQAQgCAJgFQAGgDAEgBQACAAAKgBQAEAAAVgFQAKgCALgEQAFgCAMgBIAagIIAEgBQAIgCASgDQBLgUAVgEQAVgEArgJQADgBAJgBQAIAAAFgBIALgDQAJgCAFAAQAJgBASgDQAGAAANABIARgEIAQAA");
  this.shape_61.setTransform(85.4,-50.1);

  this.shape_62 = new cjs.Shape();
  this.shape_62.graphics.f().s("#333333").ss(1.8,1,1).p("AhCkrQAAAOACARQAEAZALAUQAJARAKAeQACAHACARQABAQAEAHQAFAMAGAiIACAGIAEAMQADAHABAQQAAAcARAvQAIAZABAHQABAHADANQAEANABAGQABACAAARQAAAFAFAQQADANACAcQABAEADASQACANACAIQABADADAHQACAGABAEQAAAGACAFQAEANAAAZIAAAD");
  this.shape_62.setTransform(105.9,-15.1);

  this.shape_63 = new cjs.Shape();
  this.shape_63.graphics.f().s("#333333").ss(1.8,1,1).p("AkvBAQACABABgBQAEAAADgDQAEgBAHgDIAggGQAMgDAvgLQAkgJAXgDQAhgFAlgKIAdgIQAagGAzgLQAKgEAogFQAGgBAJgEQAJgDATgDQALgCAWgFQAUgDANgBQAHAAAUgCQARgCAKABQABAAAIABQAEABADgBQACgBADgDQAEgDABgBQAGgEAPgD");
  this.shape_63.setTransform(68,-37.7);

  this.shape_64 = new cjs.Shape();
  this.shape_64.graphics.f().s("#333333").ss(1.8,1,1).p("AkdBKIABgCQAFgCAOgFQALgEAUgDQAggIAKgEQAGgCAMgBQAMgBAHgDQAHgEAOgCQAPgEAFgCQAQgFAigHQAOgEAdgGQAOgEAbgKQAygRAhgJQAFgBAMABIAVgEQAigGALgFQAhgOAMgCQANgDAHgBIACAAQAMgBAVgC");
  this.shape_64.setTransform(83.6,22.8);

  this.shape_65 = new cjs.Shape();
  this.shape_65.graphics.f().s("#333333").ss(1.8,1,1).p("AhXlWQABgDgBgCIAAgCIgDABQgBABAAADIAAAAIAEAJQAEAIAEAQQAEATACAGIAHAVQALAkAJArQABAEALAiQABAEABALQACAJABAFQACAHAGAOQADAPAFAeQADAMAKAXIAMA9QADAKABASQACAIAEAPQAFAQACAIQABAFAJAmQAAABAGAcQAEARADALQADAIAFAPQAFAOABAKQAEAXAHAPQADAIAEAQQACAJACAGQABAFABADIACgBQABgCgFgF");
  this.shape_65.setTransform(45.3,-5);

  this.shape_66 = new cjs.Shape();
  this.shape_66.graphics.f().s("#333333").ss(1.8,1,1).p("AACgBIgCAAIAAABIAAAC");
  this.shape_66.setTransform(36.3,-39.8);

  this.shape_67 = new cjs.Shape();
  this.shape_67.graphics.f().s("#333333").ss(1.8,1,1).p("AAWjHQgCAIAAACQgCAEgBAJQgBAJgCAEQgCAFgGALQgFAKgBAFQgCAKgFARQgKAZgEAVQgBAIABASQAAALAAAWQAAACACAMQACAKAAAGIAAALIADANQADAJABARQAAAEADAJQADAJABAFQABARALAhQAAADAFALIAEAMQABADAAAGQAAAFADAD");
  this.shape_67.setTransform(33.8,-19.4);

  this.shape_68 = new cjs.Shape();
  this.shape_68.graphics.f().s("#333333").ss(1.8,1,1).p("AgQgzQABAKAFASQAGATABAHQADAdAPAUIACgC");
  this.shape_68.setTransform(-111.8,9.4);

  this.shape_69 = new cjs.Shape();
  this.shape_69.graphics.f().s("#333333").ss(1.8,1,1).p("AgQgzQACACAGAKQAHAKABAHQABAHAFAeQAEAZAHAM");
  this.shape_69.setTransform(-117.5,10.2);

  this.shape_70 = new cjs.Shape();
  this.shape_70.graphics.f().s("#333333").ss(1.8,1,1).p("AgLgtQABAAAMAtQAJAcABAS");
  this.shape_70.setTransform(-120.7,12.4);

  this.shape_71 = new cjs.Shape();
  this.shape_71.graphics.f().s("#333333").ss(1.8,1,1).p("AgZhfQAGABAFAHQABADAFAKQAKAeAHAmQABAHAGAQQAGARACAJQACAKAAAQQAAAJgBAS");
  this.shape_71.setTransform(-11.3,66.9);

  this.shape_72 = new cjs.Shape();
  this.shape_72.graphics.f().s("#333333").ss(1.8,1,1).p("AAAABIAAgB");
  this.shape_72.setTransform(-8.7,76.7);

  this.shape_73 = new cjs.Shape();
  this.shape_73.graphics.f().s("#333333").ss(1.8,1,1).p("AgWhfQgBAKAEAEQACADAHAHQAEAFAEAOQACAPACAFQAIAQACAPQABAGAFANQAAACAAAGQgBAFAAACQABAEACAHQADAGAAAEQABAIgBANQAAAHAAAO");
  this.shape_73.setTransform(-16.8,66.9);

  this.shape_74 = new cjs.Shape();
  this.shape_74.graphics.f().s("#333333").ss(1.8,1,1).p("AgZhkQAIAIAHAQQADAJAGARQAEAOAFAVQADALAFAWQAGAYACARQABAOAAAc");
  this.shape_74.setTransform(-22.3,69);

  this.shape_75 = new cjs.Shape();
  this.shape_75.graphics.f().s("#333333").ss(1.8,1,1).p("AgOhCIgFABQACAFAIAGQAEAFABAMQADANABAFQABAEAHAOQAFAIACAIQAFAQAAAk");
  this.shape_75.setTransform(-31.7,-12.7);

  this.shape_76 = new cjs.Shape();
  this.shape_76.graphics.f().s("#333333").ss(1.8,1,1).p("AgZhIQABAEADADQAGAEAAAAQAGAHADANQADAQACAFQAFAPAOAcQAKAbgDAW");
  this.shape_76.setTransform(-35.9,-11.1);

  this.shape_77 = new cjs.Shape();
  this.shape_77.graphics.f().s("#333333").ss(1.8,1,1).p("AghhNIACgFIABABQAFAEAHASQAEAHAJALQAEAHACAPQAEALANARQAEAJABAdQABAaAJAK");
  this.shape_77.setTransform(-40.3,-9.6);

  this.shape_78 = new cjs.Shape();
  this.shape_78.graphics.f().s("#333333").ss(1.8,1,1).p("AgRhiIAEABQACAEAAAIQAAAIACAFQADAFAFAKQACAIABAIQACAYAGAVQADALAAAfQAAAHgBANQABADAEASQADAQgNgF");
  this.shape_78.setTransform(-91,87);

  this.shape_79 = new cjs.Shape();
  this.shape_79.graphics.f().s("#333333").ss(1.8,1,1).p("AgOhiQAAAJAEAMQAGARAAAEQAEAZAFALQAEAJABALQAAABADAJQACAGAAAEIAABP");
  this.shape_79.setTransform(-97.5,88);

  this.shape_80 = new cjs.Shape();
  this.shape_80.graphics.f().s("#333333").ss(1.8,1,1).p("AgRhkQAIACADAIQgBAGABAFQAFAJACAQQABAFABAOQAAAMADAIQAGASABAFQAAACAAALQgBAIACAFQAEAQAAAEIAAAv");
  this.shape_80.setTransform(-104,89.8);

  this.shape_81 = new cjs.Shape();
  this.shape_81.graphics.f().s("#333333").ss(1.8,1,1).p("Aggi4QgBAHAHAPQAJASABAFQACAHAGAIQAHAKABAEQAEAJAFAUQACAHAGAOQABAFAAAJQAAAJABAEQACAIAEAOQADALAAAKQABAGACAnQACAbAAATIAAAqQABAJgDAJQgCAMgBAFIAAAH");
  this.shape_81.setTransform(-139.5,61.7);

  this.shape_82 = new cjs.Shape();
  this.shape_82.graphics.f().s("#333333").ss(1.8,1,1).p("AgljfQgBAEACAEQABADADAEQAFAKAGAbQABAGAGAKQAHALABAGIAIAjQAJAbAHA5QABAIAGATQACANACAYQAFAZAAAaQAAASAAACQABACACAHQACAFAAAFIAABY");
  this.shape_82.setTransform(-153.1,64.5);

  this.shape_83 = new cjs.Shape();
  this.shape_83.graphics.f().s("#333333").ss(1.8,1,1).p("Agwj5QgBADACgBQAEgBABADQABAEABAJQAAAJACAFIAMAkQAGAPACAHIADAaQABAHAFALQAGANABAGQACAOACAdQACAJAJAaQADAKABALQAAAHABAQQABAKAIARQADAKAEAUQADANABATQAAAYABAHQABAIAFAUQAEARAAAMIAAAw");
  this.shape_83.setTransform(-164.1,66.7);

  this.shape_84 = new cjs.Shape();
  this.shape_84.graphics.f().s("#333333").ss(1.8,1,1).p("Agti/QAEAAACACQAFAFADAJQACAGACAJQADAJAIAOQAKASACAFQANAgAJAaQAFAMADAUQAEAYACAGQAFATACAKQAEAZACAZQACAcAABQ");
  this.shape_84.setTransform(27.8,16.5);

  this.shape_85 = new cjs.Shape();
  this.shape_85.graphics.f().s("#333333").ss(1.8,1,1).p("AAAABIAAgB");
  this.shape_85.setTransform(32.5,36);

  this.shape_86 = new cjs.Shape();
  this.shape_86.graphics.f().s("#333333").ss(1.8,1,1).p("AhOkfQABAAABABQADACABAFQACAFADALQACAGAKARQAHAOADAKQAFAQAPAkQAPAhAEATQAEAOAJAhQALAdADARQADAMAMAcQADAIABAOQAAAQACAGQABAHAIAZQAFAQAAANQAAAIACAGQABAEADAIIABABQADAIAAAJQAAAFAAALQABAOAKAnQACALAAAOIgCAY");
  this.shape_86.setTransform(15.8,18.5);

  this.shape_87 = new cjs.Shape();
  this.shape_87.graphics.f().s("#333333").ss(1.8,1,1).p("Ahll9QAAAHADAGQABADAFAIQAFAJAKAaQAJAWAIAMQAHALAHATQAFALAIAVQAEAIAEASQACAFAGALQAFAKACAFQAIAVAJAoIAOAxQAFASAMAjQAGAQAEAsQACALAIAUQACAGgBAKQgBAMABAEQAAAIAFALQAFARABAFQACAcADANIAAACIAGAlQABAHAEAQQAEAOABAJQAAACgBAGQAAAFAAACQABAGAFAKQABAFAAAJQAAACACADQABAEABADQABAIAAAMQgBAHAAAO");
  this.shape_87.setTransform(2,23.1);

  this.shape_88 = new cjs.Shape();
  this.shape_88.graphics.f().s("#333333").ss(1.8,1,1).p("AlnjfIgFgCQABgCAIgEIAFgCQADAEAFABQADAAAGgBQADABAMAFQAJAEASAGQAHAEAIABQAEAAAMAAQAQAAAKAHQAEACAIAGQACABANABQADACAEAIQADAHAGACQAFADAMAAQARAAACAAIAGAAQAHACAVAGQARAFALACQAGABALACQAKACAFAEQACABADAEQADAEADABQAEABAKAAQAJgBAEABQAHACALAHQAKAJAFACIADABQAFACAVAJQARAIALADQAQAEAgAIQAbAIATALIAJAFQAuAZAjAJQAdAHAGADIACAAQAJAEADAGQADABADALQADAKAIAWQAIAVADALQABABABAIQABAFACAEQADAEABAFIABAKIACADQAEANAAACIAAAaQAAALAKAXQAFAOAAAEQACAGAEAOIAAAG");
  this.shape_88.setTransform(7.4,2);

  this.shape_89 = new cjs.Shape();
  this.shape_89.graphics.f().s("#333333").ss(1.8,1,1).p("AjVD1QAFgGAFgEIAJgGQAHgIAYgdQAEgEAHgIQAIgHACgEQADgEAGgKQAFgJAEgFQAFgEAIgHQAKgGADgFIAAAAQAFgGAHgLQAIgNAEgFQAIgLAMgOQAHgHAOgQQARgTAfgkIAagcQAFgFALgJQAEgEAFgMQAFgGALgMQAMgNAFgGQAEgHAHgHIAUgWQADgDAHgKQAGgJAFgEQABgBAEgDQAEgCABgDQADgCACgGQADgGADgDQACgCALgJIAEgDQADgEALgJQAJgJACgG");
  this.shape_89.setTransform(22,49.4);

  this.shape_90 = new cjs.Shape();
  this.shape_90.graphics.f().s("#333333").ss(1.8,1,1).p("AiTnXQABAHAFAIQACAEAFAJQADAHAAAOQABAKAJATQACAGAJAPQAHAMACAJQACAJAHAOQAIARACAFQABADAPAxQABAFACALQACAKADAGQAEAKAGAUQABADAFAJQADAHABAFQABAEAAAJQgBAIABAEQABAGAFAKQAEAKABAGQAJAfAAADQAGAPALAgQAIAcAEARQAFAUAMAfQAOAjAFAQQAOAxAPApQACAFAEAPQADANAEAHQAAABADAGQAMAWACAJQAFAgAUA9QACAKAEAaQABAKAEARQADAPACALIAAAF");
  this.shape_90.setTransform(-13.2,26.2);

  this.shape_91 = new cjs.Shape();
  this.shape_91.graphics.f().s("#333333").ss(1.8,1,1).p("AopCIIgDAGQALgGAZACQAKgBAUgGQAUgHALgBQATgBAHgEQACAAAMgHQAIgFAGgBQAIgCAQgDQAQgCAJgCQAGgCAxgJQAHgCAbgKQAVgHAMAAQAagBAfgIQARgEAlgNQAUgHApgMQAogLAUgHQAIgDAUgDQAVgEAJgDQAogPAVgFQAWgFAegBQALgBATgHQAUgHAKgBQAKgBASgIQARgHALAAQAMAAARgGQAYgIAGgBQAogIBQgVIALgDQAagHAUgJQAYgKANAA");
  this.shape_91.setTransform(-55.2,88.2);

  this.shape_92 = new cjs.Shape();
  this.shape_92.graphics.f().s("#333333").ss(1.8,1,1).p("AoYCRQAEgBAHgFQAGgFAEAAQAEgBALgCQAKgCAHgBQAOAAAXgGQANgEAXgBQAjgFAKgEIACgBQAHgCAQgIQAOgHAIgDQAfgIAUgJQAKgFAPgGQAIgDARgGQAQgGA4gQQAsgMAZgNQAIgDALAAQAGAAANgBQANgCAZgIQALgDAagFQAWgFAQgIQAPgGAagHQAegIAKgDQANgEAXgKQAGgBAPgCQAOgCAHgCQAEgBA0gLQAGgBAdgIQAUgGAOgCQAMgBAVgLIACgBIADAAQAHgCAOAAQAEgBASgFQANgEAKAAQANABATgGQAHgBAOAAQAFgBAKgEQADgBADgB");
  this.shape_92.setTransform(-82.9,-5.8);

  this.shape_93 = new cjs.Shape();
  this.shape_93.graphics.f().s("#333333").ss(1.8,1,1).p("Ah6m8IgFgQAh6m8IAAAjQAAAIADAQQADAQAAAHQAAAIACAQQADAPAAAIQAAAIAFANQAFAMAAAIQABAJAEAOQAFAQABAHQACAOADAdQABAcAHAZIACAOQABAGACAOQABALADAJQAGARAIAkQADAIAIAUQAGASADALQAEAQAKAdQAGASAJAlQABAEAIAZQABADABAGIABAPQACAQAOAhQAEANAMAaQAMAZAEAOQAAADACAKQACAHABAEQACAEAEAFQAFAGABAEQADAIAFAPQADAFAGAMQABABAPAdQACADAHARQAHAPAFABQAEgLgDgXQgCgWgHgbQgRg8gFglQgIgjgCgQQAAgTgCgKQgBgEgDgJQgEgIgBgFQgCgSgJgkQgIgkgCgSQgDgRgMgeQgNgegDgPQgEgQgIgaQgKgegBgNQgVhWgBgEQgEgPgMgdQgMgegEgPQgBgEgDgHQgEgHgBgEQgDgOgDgHQgOgfgHgPQgKgXgHgMQgEgFgCgCQgDgFgBgEQAAgGgFgJgAh6nIIAAAM");
  this.shape_93.setTransform(-123.8,55.4);

  this.shape_94 = new cjs.Shape();
  this.shape_94.graphics.f().s("#333333").ss(1.8,1,1).p("Aj+gUIAFACIAPAKQAIADAGgBQAFAAAKgDQARgDAmACQAKAAAQAEQAJADARADIAIABQAOADAVABQAMAAAXgBQAOAAAagBQAHAAANABQAIABAPACQAOACAKAAIArAAQACAAAUAEQAEACAFgBQAQAAACAAQAHACALAEQALACASgBQAKAAATgB");
  this.shape_94.setTransform(-159.1,41.6);

  this.shape_95 = new cjs.Shape();
  this.shape_95.graphics.f().s("#333333").ss(1.8,1,1).p("AkkkgQgIAPADAVQACAOAJAYQAzCPAfCWQAFAYANBxQAUBgAzgeIGdj1");
  this.shape_95.setTransform(-154.9,68.9);

  this.shape_96 = new cjs.Shape();
  this.shape_96.graphics.f("#DFE0E2").s().p("AgSDaQgNhygFgYQgfiVgziQQgJgYgCgNQgDgWAIgPIABgCIAPAJQAIAEAGgBIAPgEQARgDAmADQAKAAAOAEIAaAHQAAABAAAAQAAABAAAAQAAAAABAAQAAAAAAAAQABAAABAAQABAAAAAAQABAAAAABQABAAAAABIACANQAAAJACAFIAMAkIAIAWIADAaQABAHAFALIAHATQADAOADAdIALAjQADAKABANIABAUQABALAIARQADAKAEAUQADAMABAUQAAAYABAHIAGAcQAEARAAAMIAAAvIAFAIIhPAvQgMAHgLAAQgfAAgPhIg");
  this.shape_96.setTransform(-171.9,67.8);

  this.shape_97 = new cjs.Shape();
  this.shape_97.graphics.f("#DFE0E2").s().p("AAAD2IAAgwQAAgLgDgSIgGgbQgBgIAAgYQAAgTgEgMQgDgVgDgKQgJgRgBgKIgBgVQAAgNgEgJIgKgjQgDgegDgOIgHgSQgFgMgCgHIgCgaIgIgWIgMgkQgCgFgBgIIgCgNQAAgBAAgBQgBAAAAgBQgBAAgBAAQAAAAgBAAQgBABAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAIABQAOADAVAAIAkAAIAogBIAAABQgBAEACAEIAEAHQAFAKAGAaQABAHAGAKQAHALABAFIAKAkQAJAbAHA5IAHAdQACANACAVQAFAaAAAaIAAAUIADAJQACAFAAAFIAABYIheA3g");
  this.shape_97.setTransform(-159.4,66.1);

  this.shape_98 = new cjs.Shape();
  this.shape_98.graphics.f("#DFE0E2").s().p("AgZCIQABgFgCgFIgDgJIgBgUQAAgagFgZQgBgYgDgNIgGgbQgHg5gJgbIgKgjQgCgGgGgLQgGgKgCgGQgGgbgFgKIgEgHQgCgEABgEIAAgBIAUABIAXADQAOACAKAAIApAAIAWAEQAEACAFgBIAAABQgBAGAIAPQAJATABAEQABAHAHAIIAJAOQAEAJAFAVIAIAUIABAOIABAOIAGAWQADANABAJIADArQACAcAAASIAAAqQAAAJgCAKIgDAQIh8BKg");
  this.shape_98.setTransform(-146.8,63.5);

  this.shape_99 = new cjs.Shape();
  this.shape_99.graphics.f("#DFE0E2").s().p("AggClQADgJgBgJIAAgqQAAgTgCgbIgDgtQAAgKgDgLIgGgWIgBgNIgBgOIgIgVQgFgUgFgJIgJgOQgGgIgCgHQgBgFgJgSQgHgPABgHIAAgBIARABIATAFQAKACATAAIAdgCIASgCIADAUQABAMADAIQAGASAIAkIALAdIAJAeQAEAPAKAcIAPA3IALAcIACAJIgSACIhzBFIADgRg");
  this.shape_99.setTransform(-133.3,60.3);

  this.shape_100 = new cjs.Shape();
  this.shape_100.graphics.f("#243D42").s().p("ABvG1IgJgVIgPgdIgJgRIgIgXQgCgEgEgGIgGgIIgDgMIgDgMQgEgOgLgaQgMgagEgNQgOghgCgPIgBgQIgDgJIgJgdIgOg2QgLgegDgQIgKgbIgKgeQgJgjgFgSQgDgIgCgMIgCgUIgDgOQgGgYgBgdIgFgrQgBgHgFgQQgFgOAAgJQAAgIgFgMQgFgNgBgIQAAgIgCgPIgDgXQAAgIgDgQQgCgQAAgIIAAgjQAEAKABAFQABAFADAEIAFAHQAHAMAKAXIAVAuQAEAHADAOIAEAMIAFALQADAPANAdQAMAdADAPIAWBbIALAqQAJAbADAPQADAPANAeQANAfACAQQADASAIAkQAIAkADARIAEAOIAFANQACAKgBATQACARAIAiQAFAmASA7QAHAbACAWQACAWgEAMQgFgBgHgPg");
  this.shape_100.setTransform(-123.8,55.3);

  this.shape_101 = new cjs.Shape();
  this.shape_101.graphics.f("#DFE0E2").s().p("AmuJkIgFgDQAEgLgDgWQgCgXgHgbQgRg7gFgmQgIgigCgRQAAgSgCgKIgEgOIgFgNQgCgRgJgkQgIgkgCgSQgDgRgMgfQgNgfgDgPQgEgQgIgaIgNgrIgWhYQgEgQgMgcQgMgegEgPIgEgLIgFgLQgDgOgDgIIgVgtQgKgYgHgLIgGgIQgDgEgBgFQAAgFgFgJIgFgQIABgGQADAAAHgFQAHgFADgBIAQgCIAQgDQAPAAAXgGQAMgEAYgCQAigEALgEIACgBIAWgKQAOgHAJgDQAegIAUgKIAZgKIAagJQAPgGA4gQQAsgMAagNQAIgFALAAIATgBQAMgCAZgIIAogIQAWgFAQgIQAPgGAZgHIAngLIAkgOIAVgDIAVgEIA4gMIAigJQAVgGAOgCQALgBAVgLIACgBIADAAQAHgCAPAAIAWgGQAMgEAKAAQAOABATgGIAVgBIAUgHIABgEQABgCAIgEIABACQABAIAFAIIAHAMQADAIAAAOQABAJAJAUQACAFAJAPQAHAMACAJQACAKAHANIAKAXIAQAzIADAQQACAKADAHIAKAdIAGAMQADAHABAFQABAFAAAIIAAANIAGAPQAEAKABAGIAJAiIARAvQAKAcAEATQAFAUAMAfQAOAkAFAQQAOAuAPApIAGAVQADANAEAGIADAHQAMAXACAIQAFAgAUA9QACALAEAaIAFAbIAFAaQgFADgFAGQgNAAgYALQgUAJgaAHIgLACQhQAVgoAIIgeAJQgRAGgMAAQgLAAgRAIQgSAHgKABQgKABgUAHQgTAIgLAAQgeABgWAFQgVAGgoAOQgJAEgVADIgeAIQgUAHgoALQgpAMgSAHQglANgRAFQgfAIgZAAQgNAAgVAIIgiAKIg3AMQgJADgQACIgYAEQgGACgIAEIgOAIQgHADgTABQgLABgUAHQgUAGgKABQgZgCgLAGgAi0gTQAaBGAFAeIACAVQACAMADAJQAGARABAcQABAOAFAUIAKAjQAGACgBgJIAHAAIACAGIATgJQANgGAIgDQAFgCAMAAQALgBAGgDQAXgIAIgDIB5gbIApgHIApgIIAggJQATgGANgCIBPgTQBAgPAEABIACgIIgHguQgEgegGgRIAAgHQAAgKgHgOIgLgXQgCgHAAgJIAAgRQgCgPgIgTIgNggIgRghQgMgXgDgMQgCgOgEgJIgNgOQgIgKABgHIgDgBIADgFQgHACgSACQgPABgIADIgTAKQgKAFgJACQgSAFghALQgKAEgTADQgVAEgJADIhAAVQgfANgPAHIgYAGIgYAGQgXAJhLAWIgVAEQgNADgGAFIgDAAIgHAAQABAnAXBAg");
  this.shape_101.setTransform(-67.8,39.6);

  this.shape_102 = new cjs.Shape();
  this.shape_102.graphics.f("#ACB3B9").s().p("AjhD/IgJgiQgGgVAAgOQgBgcgGgQQgEgKgBgLIgDgWQgEgegahGQgXhAgCgnIAHAAIAEAAQAGgFAMgCIAVgFQBMgWAWgIIAZgHIAYgGQAQgGAfgOIBAgVQAIgDAUgEQAUgDAKgEQAhgLARgFQAKgCAKgFIASgJQAIgEAPgBQATgBAGgCIgDAEIAEABQgBAHAIAKIAMAPQAFAJABANQAEANALAWIARAiIAOAgQAHASACAPIAAARQAAAJADAHIALAYQAGAMABALIAAAHQAFASAEAdIAIAvIgCAHQgFAAg/APIhQASQgMACgUAGIggAJIgoAIIgpAHIh3AbQgLADgXAJQgGACgLABQgMABgFABQgIADgMAGIgUAKIgBgGIgHAAQAAAGgEAAIgCAAgAgXhdQAAAEAEAIIANAaQADAGAHAHQAIAHADAFIAFARIACAJQAAACgDACQgEADAAACQgBAEABAKIAAA0QABAFAFANQAAADgEAKQgEAHAEAHQAEgBAJgHIANgLIASgHIARgIIAMgJIAOgGQAJgLgIgMIgRgPIgHgJIgHgIQgLgFgCgCQgEgEgBgKIACABQAJACASAAIAaABIAjAFQAVABAPgCIgNg0IgBgKQAAgFgGgCQgGgCgEAEQgGAFgDAAIgaADQgRAAgKADQgLADgWAEQgBg1ABgTQgDAEgKACIgPAFIgPAHQgDABgKgBQgGgBgFACIgIgBIgFALgAgGgbQgIAGgDABQgGABgMAAIgRACQgaADgNAEIgPAHQgJADgGAAIAKATQAGANACAIQAHAXACABQAEAEAPgOIAVgVQAMgMAKgHQAFgDALgLQAKgIAGgDIgCgKIADgBQgBgGgCAAIgEABg");
  this.shape_102.setTransform(-57.2,37.8);

  this.shape_103 = new cjs.Shape();
  this.shape_103.graphics.f("#ACB3B9").s().p("AghAuQgDgBgGgXQgDgIgGgNIgKgRQAGgBAKgEIAPgHQAMgEAYgDIASgCQAMAAAGgBQADgBAIgGQAHgDABAIIgEABIACAKQgHADgJAKQgLALgFADQgKAFgNAMIgSAVQgMALgFAAIgCgBg");
  this.shape_103.setTransform(-63.3,39.6);

  this.shape_104 = new cjs.Shape();
  this.shape_104.graphics.f("#3E4535").s().p("AAXA0QgKgCgHABIgCABIgEgRQgCgFgJgHQgIgHgDgGIgOgYQgEgIABgEIAFgLIAIABQAEgCAJABQAJABAEgBIANgHIAPgFQAKgCADgEQgCATABAzIAAApIgRgEg");
  this.shape_104.setTransform(-55.6,31.1);

  this.shape_105 = new cjs.Shape();
  this.shape_105.graphics.f("#3E4535").s().p("AgrAzQAEgJAAgDQgFgOgBgEIAAgyQgBgLABgEQAAgCAEgDQADgEAAgCIgCgJIACAAQAIgBAJACIARAEQABALADAEQABADALAEIAHAJIAHAIIARAQQAIAJgJALIgOAGIgMAJIgQAIIgRAIIgNAKQgJAIgEAAQgEgHAEgHg");
  this.shape_105.setTransform(-51,42.8);

  this.shape_106 = new cjs.Shape();
  this.shape_106.graphics.f("#3E4535").s().p("AAbAjIghgGIgbgBQgRAAgKgCIgBgBIAAgnQAWgEAMgDQAJgDARAAIAZgDQACAAAGgFQAFgEAFACQAHACAAAFIAAAKIANAyQgJADgLAAIgPgBg");
  this.shape_106.setTransform(-45.3,34.2);

  this.shape_107 = new cjs.Shape();
  this.shape_107.graphics.f("#72939A").s().p("AAzFnQgEgHgDgNIgGgVQgPgpgOgxQgFgPgMgjQgMgggFgTQgEgUgKgcIgRgvIgJggQgBgFgEgLIgGgPIAAgNQAAgJgBgEQgBgFgDgHIgGgMIgKgdQgDgGgCgLIgDgPIgQg1IgKgWQgHgNgCgKQgCgIgHgNQgJgPgCgFQgJgUgBgKQAAgNgDgHIgHgNQgFgIgBgHIgBgDIAFgCQADAEAFABIAJgBIAPAGIAaAKQAIAEAIAAIAQABQAPAAALAGIAMAJIAPABQADADAEAHQADAHAFADQAGACALAAIARAAQAAAHADAGIAGALQAFAKAKAZQAJAWAIAMQAHALAHAUIANAgQAEAHAEATIAIAPIAHAPQAIAVALApIAOAuQAFASAMAjQAGATAEArQACAMAIATQACAHgBAJIAAAQQAAAIAFALQAFARABAFQACAdADAMIAAACIiEBTIgCABIgDgGg");
  this.shape_107.setTransform(-9.6,14.1);

  this.shape_108 = new cjs.Shape();
  this.shape_108.graphics.f("#72939A").s().p("AgcB6IgGgbQgDgagDgKQgTg7gGggQgCgJgMgWIACgBICChTIAGAlIAGAXIAEAXIgBAIIAAAHQABAGAFAKIABAOIACAFIACAHIABASIgBAVIAAAAQgEAFgJAGIgNALQgEAFgFAJIgJAOQgDAEgHAHIgLAMQgWAdgIAIIgIAGIgEgag");
  this.shape_108.setTransform(3.9,57.1);

  this.shape_109 = new cjs.Shape();
  this.shape_109.graphics.f("#4C868A").s().p("AgrB1IgBgUIgCgHIgCgFIgBgOQgFgKgBgGIAAgHIABgIIgFgXIgFgVIgGglIAHgFQAygiBDg5IAAACQADAHABAJIAAARQABAOAJAmQADAMgBANIgBAZIgyA3IgUAXQgMAOgIALIgLASIgMARIABgVg");
  this.shape_109.setTransform(16.4,46.5);

  this.shape_110 = new cjs.Shape();
  this.shape_110.graphics.f("#72939A").s().p("AAPDwIAAgQQABgKgCgGQgIgUgCgLQgEgsgEgSQgMgjgFgSIgOgxQgLgmgIgVIgHgPIgIgQQgEgSgEgIIgNggQgHgTgHgLQgIgMgJgWQgKgagFgJIgGgLQgDgGAAgHIAGABIAdAHIAcAHIAQADQAKACAFAEQACABADAFQADADADABQAFACAJgBQAKgBAEABQAHACAIAIQAMAIAFACIAFAQIAMAYQAIAOADAJQAEARAQAjQAOAiAFATQADAOAMAeQALAeADARQACAMAMAdQAEAJAAAOQABAQABAGQABAGAJAZIg3AlIg2AkIgRANQgFgLAAgIg");
  this.shape_110.setTransform(6.1,9.8);

  this.shape_111 = new cjs.Shape();
  this.shape_111.graphics.f("#243D42").s().p("Ag4BJQgDgNgCgcQgBgFgFgRIARgLIA0gkIA3glQAFAQAAAOQgBAHADAGIAEAMQhEA3gxAiIgHAFg");
  this.shape_111.setTransform(15,34.7);

  this.shape_112 = new cjs.Shape();
  this.shape_112.graphics.f("#72939A").s().p("AAACdQAAgGAAgQQgBgOgDgJQgMgdgDgMQgDgRgLgdQgLgfgEgOQgFgTgOghQgQgkgEgRQgDgJgIgOIgMgYIgFgQIADABIAbAMQAQAIAMADIAvAMQAaAIATALIAIAFIgHAMQAFAEADAJIAEAPQACAKAIAOIANAWQAOAhAKAYQAEALAEAUIAGAhIAGAcIgRAQQgjAXgQAOIgmAdQgJgaAAgGg");
  this.shape_112.setTransform(19.8,8.3);

  this.shape_113 = new cjs.Shape();
  this.shape_113.graphics.f("#4C868A").s().p("AglBWQABgNgDgLQgJgngBgOIAAgPQgBgJgDgHIAAgCIASgOIAogkQAZgYAQgMQACAcAABQIAAACIAGADQgHAGgEAHIgRATIgQASQgFANgDADQgKAJgEAFIgaAcg");
  this.shape_113.setTransform(27.3,35.2);

  this.shape_114 = new cjs.Shape();
  this.shape_114.graphics.f("#243D42").s().p("AgwA4QgCgGAAgIQAAgNgFgQIAmgbQARgOAggXIASgQQAEAZACAZQgRANgZAVIgoAkIgSAPIgEgMg");
  this.shape_114.setTransform(26.4,25.9);

  this.shape_115 = new cjs.Shape();
  this.shape_115.graphics.f("#E6E7EB").s().p("AgdBtIgCgPIgCgQIAAgiQgBgRABgIQAEgTAKgZIAIgbIAHgQQAEgKACgFQACgFABgIIADgOIACgKIAEAJQAEAIADAQIAHAZIAHAVQgEADgDAAQgBASgKATQgEAHgDAUQgFAPgBALQgCAKgLAaIgGAPIgDAKQgCAGgCABIgHABg");
  this.shape_115.setTransform(34.8,-28.3);

  this.shape_116 = new cjs.Shape();
  this.shape_116.graphics.f("#4C868A").s().p("Ag3BbIAAgDQAAhQgCgaIAOgLQAHgEAOgOQAMgNAJgGQAIgFAKgHIATgPIABAAQABAMAJAXIAGARIAFAUIgFABQgCAGgJAIIgOALIgEAEIgNALQgEADgCAFQgCAHgDACQAAACgCADIgGADQgFAEgFAKIgLANIgUAWg");
  this.shape_116.setTransform(37.9,26.1);

  this.shape_117 = new cjs.Shape();
  this.shape_117.graphics.f("#D9DDDC").s().p("AEqGiQgBgHACgMIACgSIAAgeQABgiACgOQABgEAAgRIgBgDIACgBIAhgDIAEgDIAAgEQAAgZgEgNQgCgFgBgGIgCgKIgEgKQgCgIgDgNIgDgWQgCgcgDgNIgGgVIAAgTIgFgTIgFgUQAAgHgIgZQgTgvAAgcQgCgQgCgHIgFgMIgBgGQgGgigGgMQgDgHgBgQQgDgRgCgHQgJgegJgRQgLgUgEgZIgGABIgCgKIgBgMIgBAAQgOADgGAEIgFAEQgDAEgCAAQgDABgEgBIgJgBQgKgBgRACIgcACQgMABgUADIghAHQgTADgJADQgHAEgGABQgpAGgJADQg1AMgaAHIgdAIQglAKghAFQgXADgkAJIg8AOIgfAGIgLAEIgHgVIgHgZQgDgQgEgIIgEgJIAAAAIABgEIADgBIAAACIAOgGIARgDIAOgEIAPgDQAJgBAUABIAXgDQAGgBALgEQALgFAGgBIAOgBQAHAAAGgCQAdgLAfgEQANgCA1gQIAUgFIAZgLQAIgCAQAAIAggHIAYgFQASgCAJgCIAagHIAWgGIAagDQAQgCAIgFQAHgDADAAIAMgBQAFAAAVgGIAUgGQAFgBANgBIANgEIABAAQgBAHAFAQQABAKAFAPIAGAZIAHAXIAFAWQAFAXAJAXIAMAmQACAHABARQABAPADAIIAEALIAEALIABAPIABAGIAFALIADALIACAWIAEAMIAFAOIADAOIAJArIAEAaIAFAaQAIAeACARIADAXQAEAOABAGQABAUAFANIAHAOQAEAIAAAHQABALAGAWIAAADIADAEQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAARAFAXIAIApIAFAdIADAJIABAMQABAGAEAFIAAgBQABACACAEIgDACQgGAAgGADIgMAFQgLADgXADIgdAEQgIABgaAIg");
  this.shape_117.setTransform(78.1,-13.2);

  this.shape_118 = new cjs.Shape();
  this.shape_118.graphics.f("#E6E7EB").s().p("AA1E5QgMgHgTgIIgagQQgMgKgEgBIgFgCIAEgEIAOgNQAIgIABgGIAFgBIgFgUIgEgSQgJgXgBgLIAAgaIgEgPIgBgDIgCgKQgBgFgCgEIgDgJIgCgJIgLggIgLggQgEgLgCgDQgEgGgJgCIgBAAQgDgDgBgGIAAgJIgFgMIgFgOQgNgggBgRQAAgGgDgIIgEgNQAAgRgDgKIgDgMIAGgBQACgBADgGIADgKIAGgPQANgaABgKQABgLAFgPQADgUAFgJQAKgTAAgSQAEAAADgDQALAkAJArIAMAmIACAPIADAOIAIAVIAGAtQADAMAKAXIAOA/QADAKABAQIAGAXIAHAYIAKArIAGAdIAHAcIAIAXQAFAOABAKQAEAXAHAPIAHAYIAGAXIgBAFQABAEgDADIgEAHIgFAOIgdADIgRgNg");
  this.shape_118.setTransform(42.9,0.1);

  this.shape_119 = new cjs.Shape();
  this.shape_119.graphics.f("#72939A").s().p("AgOBaIgGggQgEgUgEgMQgKgagPgfIgMgWQgIgOgCgJIgEgPQgDgKgFgEIAHgMQAuAZAiAJQAdAHAGADIABAAQAJAEAEAGQACADAEALIALAgIALAeIACAJIADAJQACAEABAFIACAKIABADIgBABQgJgCgKAIIgQANQgLAGgfAWIgSARIgGgcg");
  this.shape_119.setTransform(32.3,7.2);

  this.shape_120 = new cjs.Shape();
  this.shape_120.graphics.f("#243D42").s().p("AgxAHIAUgQQAdgVAKgHIARgNQAJgIAJACIACAAIAEAPIAAAZIgCAAIgTAQQgJAFgLAFQgJAFgKANQgNAOgHAFIgOAKQgCgZgEgZg");
  this.shape_120.setTransform(36.5,18.3);

  this.shape_121 = new cjs.Shape();
  this.shape_121.graphics.f("#E6E7EB").s().p("AhTCNQgKgXgDgMIgIgtIgIgWIgDgNIgCgPIgMgkQgJgrgLgkIALgEIAggHIA7gOQAkgIAVgDQAhgFAlgKQAKAQAFANQADAKACASQADAMAJAWQAIAZAJAzQABAEAGAKQAFAIABAFQABADgBAGIgBAJQABAFAFAGIADARQg6AUgbAJQgwAPglAIQgGAAgHAFIgNAFIgYAHIgJACg");
  this.shape_121.setTransform(53.3,-22);

  this.shape_122 = new cjs.Shape();
  this.shape_122.graphics.f("#4C868A").s().p("Ah3CFQgFgBgKgIQgGgFgLgEIgUgGIgPgEQgIgDgFgDIgegQQgQgHgfgRQgHgEgJgJIAdgDIAFgOIAFgHQACgDgBgEIACgFIABgBIAFAAIATgHQALgCAVgDQAggHAKgEQAGgDAMgBQAMgBAHgDQAHgDANgDIAVgFQAQgGAhgGQAPgFAbgGQAOgEAdgMQAxgQAhgJQAGgBALAAIAWgEQAigGALgEQAhgOAMgDQAMgDAIAAIABADQAAARgBAEQgDAOAAAiIAAAeIgCASQgCAMABAFIAAACIgJADQgdAHguAQQhRAagUAJQgkAOgQACQgJABgNAFIgVAHQgiAMgSAEIgiAMIgOADIgOADIgFACIgCAAIgEAAg");
  this.shape_122.setTransform(79.3,28.1);

  this.shape_123 = new cjs.Shape();
  this.shape_123.graphics.f("#789196").s().p("AhKC9IgHgXQgHgPgDgYQgCgKgFgNIgIgXIgHgdIgGgdIgKgpIgHgXIgFgYQgCgSgDgKIgKgvIAJgCIAZgHIAMgGQAHgEAGgBQAngHAwgPQAZgJA6gUIAEALQAHAPACALIAAAHIgBAHQACAGAFAJQAHAIABAGIAAAGIgBAHIAKAgQALApABALIABATQAAALACAGQACAJAHATQAGARACALIAKAnQAGAZgCAQIACARQghAHgQAFIgVAGQgNACgHAEQgHADgMABQgMABgGACQgLAEgdAIQgVADgLAEIgTAHIgFAAIgCAAIgGgXg");
  this.shape_123.setTransform(61,7.8);

  this.shape_124 = new cjs.Shape();
  this.shape_124.graphics.f("#E6E7EB").s().p("Ah6CNQgFgGgBgFIAAgJQACgGgCgDQgBgFgFgIQgFgJgBgFQgKg1gHgZQgKgUgCgMQgDgSgCgKQgFgNgKgQIAdgIQAagHA1gNQAJgDApgFQAFgCAKgEQAJgCARgEIAhgGQAUgEAMAAIAbgCQARgCAKABIAJABQAFABADgBQACgBADgDIAFgEQAGgEAPgDIAAAAIABAMIACAKQADANABAXIACAiQACAOgBAWIAAAiIAAAPIAAAOIADAXIgDADIAAADIgaAGIgaAIIglALIglALIglAKQgJABgNAGIgTAIQgfAJhIAZg");
  this.shape_124.setTransform(80.5,-29.3);

  this.shape_125 = new cjs.Shape();
  this.shape_125.graphics.f("#B0B1B3").s().p("AgWBhIADgEIgDgWIgBgPIABgPIAAgjQABgTgCgPIgCgjQgCgWgCgNIAGgBQADAYAMAVQAIARAIAeQACAGACAQQACAPADAIQAGAMAGAhIABAGIgCABQgEABgDgDQgDACgFAAIgJABIgTAHIgHACg");
  this.shape_125.setTransform(101.6,-33);

  this.shape_126 = new cjs.Shape();
  this.shape_126.graphics.f("#243D42").s().p("AA4CiIgPgYQgOgagDgRIgIgZIgJgYQgOgugCgMQAAgEgCgEIgEgGIgEgQIgIgQIgMgoIgTgyQgGgRAAgLIAGgBIAVgIIAJAAQAGAAADgCQADADADgBIADgBIAFAMQACAHABAQQABAcAQAxQAIAZABAHIAEAUIAFAUIABARIAFAUQADANACAcIAEAWQACANACAIIAEAKIADAKQABAGABAFQAFANAAAaQgBgMgJgPg");
  this.shape_126.setTransform(105.8,-5.2);

  this.shape_127 = new cjs.Shape();
  this.shape_127.graphics.f("#D9DDDC").s().p("Ah/CtIgBgPIgEgLIgEgKQgDgIgBgQQgCgQgCgIIgMgmQgIgWgFgXIgGgVIgGgWIgGgZQgFgQgBgJQgGgRACgGIgBgBIAMgEIAEgBIAagFQBLgUAVgEIA+gNIAMgCIANgBIALgDIAOgCIAbgEIATABIANgDIAbAAQADAFAAAMQABAIADANIAFAWIACAUQACAMADAIQAIAOAAADQACAGAAAMQABAGAIARQAEAGAAAIQABAEAEAHIAHANQAFALAAAXIACAQIgLACQgNAGgcAHQgoAMgUAFIgPAFIgOAGQgZAHgMAFQgSAJgQAAQgLABgXAKQgLAFgPABQgGABgJAEIgPAGIgNAAQgHABgBAGg");
  this.shape_127.setTransform(121.2,-44.1);

  this.shape_128 = new cjs.Shape();
  this.shape_128.graphics.f("#789196").s().p("AiIDWQACgQgHgZIgKgnQgCgLgGgRQgHgTgCgJQgCgIAAgLIgBgTQgBgLgLgnIgKggIABgHIABgGQgCgGgGgIQgGgJgCgGIABgHIAAgHQgCgLgHgPIgEgLQBIgZAfgJIAVgIQANgGAIgBIAmgLIAkgKIAjgMIAbgHIAagGQAAAKAHARIASAzIANAoIAHAPIAEARIAEAGQACADAAAEQADAMAPAwIAJAXIAIAZQADAQAOAaIAPAZQAJAOABAMIAAADIgEAEIghADIgCAAQgIABgMADQgMACghAOQgLAFgiAGIgWAEQgLgBgGABQggAJgwARQgdAMgOAEQgdAGgPAEg");
  this.shape_128.setTransform(90.4,0.2);

  this.shape_129 = new cjs.Shape();
  this.shape_129.graphics.f("#9AA49C").s().p("AgHCaQgFgVgBgMQgBgHgDgIIgHgNQgFgNgCgUQAAgGgFgOIgCgXQgCgRgIgdIgFgaIgFgaIgIgsIgEgOIgFgOQAHAEARAIIAPAJQAXALAEADQAJAIAgAMQAEADAKAAQAJABAFACIALAGQADACABACIAAABQABAEgHAPQgDAKgKARIgGANIgFANIgFAPQgCAKgDAGQgHAJgDAFQgCAFgBAHIgBANIgGAQQgGAKgBAFQgIAegBAJQgGAQABAHg");
  this.shape_129.setTransform(117.4,-5);

  this.shape_130 = new cjs.Shape();
  this.shape_130.graphics.f("#9AA49C").s().p("AirB7IgDgEIgBgDIABAAQgBgIAGgQQADgIAIgeQABgGAGgKIAGgQIABgMQABgIACgCIAKgOQADgGACgLIAFgRIAFgMIAGgNQAKgSADgJQAHgQgBgEIABgCIAFAAQAFAHAPAHQAHADAIAIQAJAKAFADIATALQAOAGAEAEQAMAIAaANIAUAJQAGADANAJQAHAEAMAKQAMAJAHAEIAdATIAUAMQAKAEAAADIABACQgEADgFABIgFAAIgBAAIgDgEIAAADIADABIABAAIgCAAIgTADIgTADQgNACgHACQgnAKgTAIQgIADgPAAQgQAAgFADQgJAEgQAEIgYAHQgUAKgLAAQgQAAgJACQgdAIgMAAQgIAAgFABIgIADIgCAAIgCAAg");
  this.shape_130.setTransform(134.2,-1.1);

  this.shape_131 = new cjs.Shape();
  this.shape_131.graphics.f("#9AA49C").s().p("AgdBuQgEgCgKgBQgJAAgEgDQgggMgLgIQgEgDgXgLIgQgIQgQgJgHgEIgDgMIgCgWIgEgLIgEgJIgCgHIAEAAQABgGAHAAIANgBIAOgGQAKgEAGgBQAPgBAKgFQAYgKAKgBQATAAASgJQAMgFAXgHIAOgFIAOgFQAUgGApgMQAbgHAOgGIAKgCIAMAAIALgBIALgDIgEAEIgJAMIgQAOIgJANIggAdQgWARgJANIgLAOQgOANgHAJQgNAZgLAMQgTAbgKAOQgKAMAAACIgBACIgMgHg");
  this.shape_131.setTransform(126.4,-25.4);

  this.shape_132 = new cjs.Shape();
  this.shape_132.graphics.f("#9AA49C").s().p("AhyB4QgBgCgDgCIABgBQAAgCALgNQALgNAUgbQAKgMAOgZQAGgJAPgOIAKgOQAJgMAUgRIAggdIAKgNIAQgPIAIgLIAFgFIAJgEIACAAQAEgBABADIAAAHIAEAVQACAKADATIADAdIABAGQAFAaAAAVIABANIADAHIAAAPIABAEIgbAFIgHABIgSAGIgRAFQgaAIgOABQgNACgWAHIglANQgWAIgOACIgKAAIgFABIgBACg");
  this.shape_132.setTransform(136.5,-25.4);

  this.shape_133 = new cjs.Shape();
  this.shape_133.graphics.f("#9AA49C").s().p("AB3BnIgUgLIgdgTQgHgEgMgLQgNgLgHgEQgMgJgHgDIgRgJQgagNgMgHQgGgDgOgGIgUgKQgEgDgJgKQgIgIgHgDQgPgHgGgIIAKAAQAPgCAWgIIAkgNQAWgHAQgCQALgBAbgIIARgFIARgGIAIgBIAAAFQAAAEACAGIADALIACAQQACAMAGAOIAHAXQANAtAPApIAMAfIABAFIAAAEIgCABIAAABIgBAAQgBgDgJgEg");
  this.shape_133.setTransform(138.8,-7.8);

  this.shape_134 = new cjs.Shape();
  this.shape_134.graphics.f("#506C70").s().p("ABgA5QgEgCgIABIgLABIgaABQgQgBgKgCQgVgEghABIg4ABIgDABQgFgOgCgNIgDgPIgDgLQgCgFABgEIgBgFIAbgEIADgBIATgIQALgFAJgBIAfgEQAIgBATgJQAFgCAIAAIANgCIAFgDQAEgBAKABQAHAAALgGIADAIIADAPIAFAcIADAKIADANIABAQIAEALIADALIgBAHIgLgDg");
  this.shape_134.setTransform(156.6,-17.4);

  this.shape_135 = new cjs.Shape();
  this.shape_135.graphics.f("#E3E5E2").s().p("AhNBdIAAgPIgDgHIgBgNQAAgVgFgcIgBgGIAAAAQAMgBAWgUQAagZATgMQAMgJAWgSQAPgPAFABQABALADAJIAGAXIAGAWQAJAeACAHQABAJAFANIADAQIAGAMQgLAFgHAAQgKgBgFACIgEADIgNABQgIAAgFACQgUAJgHACIggADQgIABgMAFIgTAIIgDABg");
  this.shape_135.setTransform(156.1,-29.1);

  this.shape_136 = new cjs.Shape();
  this.shape_136.graphics.f("#A6B0A8").s().p("AiHB7IgRgPQgKgIgGgHIgEgFQgCgEgBgCIAAABQgEgFgBgGIgBgMIgDgJIgFgdIgIgnQgFgXAAgRIAJgDQAEgBAJAAQALAAAdgIQAJgCAQAAQALAAAUgKIAYgHQAQgEAJgEQAHgDAQAAQAOAAAHgDQATgIAngKQAIgCAMgCIATgDIAUgDIABAAIAFAAQAFgBAEgDIAAgCIAAgBIADAJIAFARIAHAQIADAQQABAEAEAHIAEATIAFAQQADANAGAQIAMAbQADAIAGAdIgDAAIgUAGQgEACgNABIgQAEIgKABQgbAEgZAJIgfAMQgJAEgRADQgRADgJACQgSAIggAHIgWADIgNAEQgJADgFAAIgOgBQgKAAgEADg");
  this.shape_136.setTransform(137.7,17.1);

  this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_136},{t:this.shape_135},{t:this.shape_134},{t:this.shape_133},{t:this.shape_132},{t:this.shape_131},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-185.8,-103.3,371.9,206.8);


(lib.NewSymbol = function(mode,startPosition,loop) {
  this.initialize(mode,startPosition,loop,{});

  // Layer 1
  this.shape = new cjs.Shape();
  this.shape.graphics.f("#000000").s().p("AgNAOQgFgGAAgIQAAgHAFgGQAGgFAHAAQAIAAAGAFQAGAGgBAHQABAIgGAGQgGAGgIgBQgHABgGgGg");

  this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2,-2,4,4);


(lib.Starts = function(mode,startPosition,loop) {
  this.initialize(mode,startPosition,loop,{});

  // New_Symbol
  this.New_Symbol = new lib.NewSymbol();
  this.New_Symbol.parent = this;
  this.New_Symbol.setTransform(660.2,-125);
  this.New_Symbol._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol).wait(20).to({_off:false},0).to({x:-364.7,y:145},29).wait(1));

  // New_Symbol
  this.New_Symbol_1 = new lib.NewSymbol();
  this.New_Symbol_1.parent = this;
  this.New_Symbol_1.setTransform(625.4,-36);
  this.New_Symbol_1._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_1).wait(11).to({_off:false},0).to({x:-399.5,y:234},29).to({_off:true},1).wait(9));

  // New_Symbol
  this.New_Symbol_2 = new lib.NewSymbol();
  this.New_Symbol_2.parent = this;
  this.New_Symbol_2.setTransform(643.8,344.3);
  this.New_Symbol_2._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_2).wait(3).to({_off:false},0).to({x:-381.2,y:614.3},29).to({_off:true},1).wait(17));

  // New_Symbol
  this.New_Symbol_3 = new lib.NewSymbol();
  this.New_Symbol_3.parent = this;
  this.New_Symbol_3.setTransform(518,310.8);
  this.New_Symbol_3._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_3).wait(16).to({_off:false},0).to({x:-507,y:580.8},29).to({_off:true},1).wait(4));

  // New_Symbol
  this.New_Symbol_4 = new lib.NewSymbol();
  this.New_Symbol_4.parent = this;
  this.New_Symbol_4.setTransform(512,218.4);
  this.New_Symbol_4._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_4).wait(9).to({_off:false},0).to({x:-513,y:488.4},29).to({_off:true},1).wait(11));

  // New_Symbol
  this.New_Symbol_5 = new lib.NewSymbol();
  this.New_Symbol_5.parent = this;
  this.New_Symbol_5.setTransform(-243.1,264.3);
  this.New_Symbol_5._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_5).wait(1).to({_off:false},0).to({x:-490.5,y:329.4},6).wait(20).to({x:534.5,y:59.4},0).to({x:-243.1,y:264.3},22).wait(1));

  // New_Symbol
  this.New_Symbol_6 = new lib.NewSymbol();
  this.New_Symbol_6.parent = this;
  this.New_Symbol_6.setTransform(590.4,5.3);
  this.New_Symbol_6._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_6).wait(1).to({_off:false},0).to({x:-434.6,y:275.3},29).to({_off:true},1).wait(19));

  // New_Symbol
  this.New_Symbol_7 = new lib.NewSymbol();
  this.New_Symbol_7.parent = this;
  this.New_Symbol_7.setTransform(675.3,22);
  this.New_Symbol_7._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_7).wait(6).to({_off:false},0).to({x:-349.7,y:292},29).to({_off:true},1).wait(14));

  // New_Symbol
  this.New_Symbol_8 = new lib.NewSymbol();
  this.New_Symbol_8.parent = this;
  this.New_Symbol_8.setTransform(788.1,155.4);
  this.New_Symbol_8._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_8).wait(12).to({_off:false},0).to({x:-236.8,y:425.4},29).to({_off:true},1).wait(8));

  // New_Symbol
  this.New_Symbol_9 = new lib.NewSymbol();
  this.New_Symbol_9.parent = this;
  this.New_Symbol_9.setTransform(892.3,239.5);
  this.New_Symbol_9._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_9).wait(17).to({_off:false},0).to({x:-132.7,y:509.5},29).to({_off:true},1).wait(3));

  // New_Symbol
  this.New_Symbol_10 = new lib.NewSymbol();
  this.New_Symbol_10.parent = this;
  this.New_Symbol_10.setTransform(859.6,312.1);
  this.New_Symbol_10._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_10).wait(7).to({_off:false},0).to({x:-165.4,y:582.1},29).to({_off:true},1).wait(13));

  // New_Symbol
  this.New_Symbol_11 = new lib.NewSymbol();
  this.New_Symbol_11.parent = this;
  this.New_Symbol_11.setTransform(739.8,291);
  this.New_Symbol_11._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_11).wait(13).to({_off:false},0).to({x:-285.1,y:561},29).to({_off:true},4).wait(4));

  // New_Symbol
  this.New_Symbol_12 = new lib.NewSymbol();
  this.New_Symbol_12.parent = this;
  this.New_Symbol_12.setTransform(581.6,262.1);
  this.New_Symbol_12._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_12).wait(19).to({_off:false},0).to({x:-443.4,y:532.1},29).to({_off:true},1).wait(1));

  // New_Symbol
  this.New_Symbol_13 = new lib.NewSymbol();
  this.New_Symbol_13.parent = this;
  this.New_Symbol_13.setTransform(611.6,316.7);
  this.New_Symbol_13._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_13).wait(8).to({_off:false},0).to({x:-413.3,y:586.7},29).to({_off:true},1).wait(12));

  // New_Symbol
  this.New_Symbol_14 = new lib.NewSymbol();
  this.New_Symbol_14.parent = this;
  this.New_Symbol_14.setTransform(540.4,-58.4);

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_14).to({x:-484.5,y:211.6},29).to({_off:true},1).wait(20));

  // New_Symbol
  this.New_Symbol_15 = new lib.NewSymbol();
  this.New_Symbol_15.parent = this;
  this.New_Symbol_15.setTransform(575.4,-131);
  this.New_Symbol_15._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_15).wait(18).to({_off:false},0).to({x:-449.5,y:139},29).to({_off:true},1).wait(2));

  // New_Symbol
  this.New_Symbol_16 = new lib.NewSymbol();
  this.New_Symbol_16.parent = this;
  this.New_Symbol_16.setTransform(758.3,-115.7);
  this.New_Symbol_16._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_16).wait(15).to({_off:false},0).to({x:-266.6,y:154.3},29).to({_off:true},1).wait(5));

  // New_Symbol
  this.New_Symbol_17 = new lib.NewSymbol();
  this.New_Symbol_17.parent = this;
  this.New_Symbol_17.setTransform(935.5,-86.7);
  this.New_Symbol_17._off = true;

  this.timeline.addTween(cjs.Tween.get(this.New_Symbol_17).wait(14).to({_off:false},0).to({x:-89.5,y:183.3},29).to({_off:true},1).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(538.4,-60.4,4,4);


(lib.Sattelite = function(mode,startPosition,loop) {
  this.initialize(mode,startPosition,loop,{});

  // Layer 1
  this.instance = new lib.Tween6("synched",0);
  this.instance.parent = this;
  this.instance.setTransform(178.1,103.4);

  this.timeline.addTween(cjs.Tween.get(this.instance).to({x:177.1,y:106.4},24).to({x:178.1,y:103.4},25).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.7,0,371.9,206.8);


// stage content:



(lib.Satellite2 = function(mode,startPosition,loop) {
  this.initialize(mode,startPosition,loop,{});

  this.stop();
  this.invPlaying = false;

  // timeline functions:
  this.frame_0 = function() {
    if (this.invPlaying === false) {
      this.stop();
    } else {
      this.play();
    }
  }

  // actions tween:
  this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(50));

  // stars
  this.stars_mc = new lib.Starts();
  this.stars_mc.parent = this;
  this.stars_mc.setTransform(277.6,269.4,1,1,0,0,0,213.8,239.6);

  this.timeline.addTween(cjs.Tween.get(this.stars_mc).wait(50));

  // Layer 4
  this.satellite_mc = new lib.Sattelite();
  this.satellite_mc.parent = this;
  this.satellite_mc.setTransform(305.5,209.5,1,1,0,0,0,185.2,102.4);

  this.timeline.addTween(cjs.Tween.get(this.satellite_mc).wait(50));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(387.7,269.4,493.5,344.3);

})(defineLib = defineLib||{}, defineImages = defineImages||{}, createjs = createjs||{}, ss = ss||{});
var defineLib, defineImages, createjs, ss;
